# Generated by Django 5.2.4 on 2025-07-04 21:22

import jsonfield.fields
from django.db import migrations, models


def populate(apps, schema_editor):
    AlterFieldModel = apps.get_model('alterfield', 'AlterFieldModel')

    AlterFieldModel.objects.create(data=1)
    AlterFieldModel.objects.create(data="foobar")
    AlterFieldModel.objects.create(data={"foo": "bar"})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlterFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RunPython(populate, migrations.RunPython.noop)
    ]
