# Generated by Django 5.2.4 on 2025-07-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alterfield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alterfieldmodel',
            name='data',
            field=models.JSONField(),
        ),
    ]
